sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=oldest-lib
  - TOX_ENV=pinned-lib
  - TOX_ENV=latest-lib
  - TOX_ENV=mastereventlet-lib
  - TOX_ENV=branchcoverage-lib

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=mastereventlet-lib
    - env: TOX_ENV=branchcoverage-lib

script:
  - tox
