sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox-travis

env:
  - FACTOR=oldest
  - FACTOR=pinned
  - FACTOR=latest
  - FACTOR=mastereventlet

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: FACTOR=examples
    - python: 3.4
      env: FACTOR=examples
    - python: 2.7
      env: FACTOR=branchcoverage
    - python: 3.4
      env: FACTOR=branchcoverage
    - python: 3.4
      env: FACTOR=docs

  allow_failures:
    - env: FACTOR=mastereventlet
    - python: 3.4
      env: FACTOR=branchcoverage

script:
  - tox
