sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox-travis

env:
  - DEPS=oldest
  - DEPS=pinned
  - DEPS=latest
  - DEPS=mastereventlet

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOX_ENV=py27-examples
    - python: 3.4
      env: TOX_ENV=py34-examples
    - python: 3.4
      env: TOX_ENV=py34-branchcoverage-lib
    - python: 3.4
      env: TOX_ENV=docs

  allow_failures:
    - env: DEPS=mastereventlet
    - env: TOX_ENV=py34-branchcoverage-lib

script:
  - tox
