sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox-travis

env:
  - DEPS=oldest
  - DEPS=pinned
  - DEPS=latest
  - DEPS=mastereventlet
  - TASK=lib

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TASK=examples
    - python: 3.4
      env: TASK=examples
    - python: 3.4
      env: TASK=branchcoverage
    - python: 3.4
      env: TASK=docs

  allow_failures:
    - env: DEPS=mastereventlet
    - env: TASK=branchcoverage

script:
  - tox
